FROM elixir:1.8.1 as base

# Handle locales
RUN apt-get update && \
        apt-get install --yes locales libsnappy-dev && \
        sed -i '/^#.* en_US.UTF-8 /s/^#//' /etc/locale.gen && \
        locale-gen

ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en"

# Install build utils
RUN apt-get install --yes \
        wget \
        unzip \
        build-essential \
        apt-transport-https \
        libssl1.1 \
        git

WORKDIR /opt/app

COPY . ./

RUN  rebar3 compile
